# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 04:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_activity_activity_zone_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsspu',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品spu详情'),
        ),
    ]
