# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0002_auto_20190129_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='hpropre',
            new_name='hproper',
        ),
    ]
