# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0004_auto_20190202_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_tuijian',
            field=models.BooleanField(default=False, verbose_name='是否默认推荐'),
        ),
    ]
