# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='detail_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
