# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 06:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_detail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='change_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='detail_address',
            field=models.CharField(max_length=200, null=True, verbose_name='现住地址'),
        ),
        migrations.AlterField(
            model_name='users',
            name='home_address',
            field=models.CharField(max_length=200, null=True, verbose_name='老家地址'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nickName',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(2, '昵称至少为2个字符')], verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phoneNum',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d+{9}$', '手机号码格式错误')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='school',
            field=models.CharField(max_length=200, null=True, verbose_name='学校名称'),
        ),
    ]
