# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 07:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190120_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.DateField(null=True, verbose_name='生日日期'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phoneNum',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误')], verbose_name='手机号'),
        ),
    ]
