# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190120_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='head',
            field=models.ImageField(default='head/hlwtx.jpg', upload_to='head/%Y%m', verbose_name='用户头像'),
        ),
    ]
